import Head from 'next/head'
import { useState } from 'react';
import {Footer, Intro, Navbar, Skills, Works } from '../components'

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark": ""}>
      <Head>
        <title>KGT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white dark:bg-slate-900'>
        <div className=' min-h-screen mx-5 md:mx-20'>
          <Navbar darkMode={darkMode} setDarkMode={setDarkMode}/>
          <Intro/>
          <Skills/>
          <Works/>
          <Footer/>
        </div>
      </main>
        
    </div>
  )
}
